### ISSUE TITLE
"Open image in new tab" function changed

### ISSUE THREAD

**Issue by Liz-chan** [kubuzetto/behind#11]
Before the latest update, I used to be able to right click an image and open it in a new tab in the extension view, and it would have the URL of the source website, but now it just leads to a blob URL which breaks my workflow since my other extensions can't act on it. 

For example, if you right click and open in new tab, this is the URL it leads to: `blob:chrome-extension://blfpdedbdighagggfhgihcocfheicfjk/f41ad91f-64c5-4570-94ed-547164a1436a`

While before it lead to the actual image URL.

**Comment by kubuzetto** [comment]
Hi Liz-chan, thank you for the bug report! The behavior change here is a result of the fix to [issue #10](https://github.com/kubuzetto/behind/issues/10).

Instead of "Open Image in New Tab", if you use the "Open **Link** in New Tab" option; that will lead you to the original image URL instead of the blob. Does that option work with your workflow?

**Comment by Liz-chan** [comment]
Ah yeah, doing it that way works, but I preferred the link itself being there automatically rather than having to press Ctrl-S every time. To be more specific, I use an extension which retrieves the maximum size of an image on the server if it's been downscaled with arguments in the URL, and with behind it would open the image automatically and the extension would do its thing, but now there's another step I have to go through.

**Comment by kubuzetto** [comment]
I'll be looking further into this. The previous approach simply didn't work at all in certain pages, so I had to change it; but I believe I can find a middle ground here, allowing both behaviors.

Would you be willing to share the name of the other extension, so that I can test them together myself?

**Comment by Liz-chan** [comment]
> Would you be willing to share the name of the other extension, so that I can test them together myself?

Sure, it's here https://github.com/qsniyg/maxurl

**Comment by kubuzetto** [comment]
Hi again,
I just released 0.2.14; which makes the 'fetch as blob' behavior in 0.2.13 optional (i.e. it is invoked only if the original method fails to load the image). Can you check if the desired behavior is satisfied?

**Comment by Liz-chan** [comment]
Oh yeah it works great, ty
