### ISSUE TITLE
NEW - When I save a photo the photo name comes up as "index" on all photos

### ISSUE THREAD

**Issue by bythec1** [kubuzetto/behind#12]
This is a recent problem.  When I click on a photo to save and the SAVE AS window comes up the name of ALL photos is "index" instead of the photo name.  I can, of course, name the photo myself but I didn't have to do that before.

**Comment by kubuzetto** [comment]
Hi bythec1, thank you very much for the bug report!
This is due to a fix I released for issue #10, unfortunately it interfered with the workflow of several users, including yourself.
I tried to make it conditional in 0.2.14, which I just released. Can you try it with the new version and verify that the problem is resolved? Thanks!

**Comment by bythec1** [comment]
Excellent!  It is working great again!  Thank you for your hard work and quick response!!!


On 5/5/2021 1:32:04 PM, Devrim Şahin ***@***.***> wrote:
Hi bythec1, thank you very much for the bug report!
This is due to a fix I released for issue #10 [https://github.com/kubuzetto/behind/issues/10], unfortunately it interfered with the workflow of several users, including yourself.
I tried to make it conditional in 0.2.14, which I just released. Can you try it with the new version and verify that the problem is resolved? Thanks!

**Comment by kubuzetto** [comment]
Awesome, thank you!
