### ISSUE TITLE
Images in blob URL not being shown

### ISSUE THREAD

**Issue by nafarinha** [kubuzetto/behind#21]
Hi, based on a previous issue, video data in blob URLs won't be supported but what about images? In this example, Behind doesn't show any of the images (https://storymaps.arcgis.com/stories/401df732d612490e80cf111e561e05cd). Although it seems to detect a image when I right-click on one, when I then click on behind from the context menu and open the new tab, it doesn't show any image, just some metadata (e.g. svg%3EOriginal image size: 2300px to 2300px).  I'm running Firefox 96.0.2 (64-bit) on Windows 10.0.19042.1466. Thank you for the extension!!

![image](https://user-images.githubusercontent.com/1145780/150942045-b15cc748-691c-4b12-9f5a-04b9b71c3b7e.png)

![image](https://user-images.githubusercontent.com/1145780/150942001-ce0cf21c-da4e-4ff1-8cd4-0bc7bed275be.png)

**Comment by kubuzetto** [comment]
Thank you for the bug report @nafarinha! I think you discovered an interesting case.

Normally, the limitation that applies to video blobs also apply to image blobs; that is, we shouldn't be able to download them via the add-on. Normally the add-on shouldn't be able to detect any viable images under the cursor; however it mistakenly captures some empty inlined `<svg>` image, causing the confusion (I'm getting into details to let you know that even if I fix this; the image **will not be downloadable** via _behind!_).

My initial suspicion is that the image lazily loaded; and the DOM element is dynamically replaced using javascript; so the add-on encounters the svg element but we cannot (when we inspect DOM elements manually).

I'll be looking further into this.

**Comment by nafarinha** [comment]
No problem :) Glad to provide some help to crush the bug! Ty for your work with the extension!

**Comment by kubuzetto** [comment]
Hi @nafarinha, I'm back with some boring updates :)

I finally had a chance to properly investigate this issue. It turns out that the empty <svg> tag that behind! seemed to conjure out of thin air, in fact does appear in the page elements. The webpage does some tricks to obscure the image URLs (first loads them; then replaces the items with a canvas hidden behind a huge empty svg tag etc.), and the extension picks up on that empty svg tag. Long story short; I thought this was a bug; but it's not. If that's OK, I'm closing the issue.
